stages:
  - build
  - deploy

build-package:
  image: node:18-alpine3.17
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
  only:
    - main
    - deploy

deploy-container-image:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - pwd
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - deploy
  dependencies:
    - build-package